Data <- read.table(file="household_power_consumption.txt", header=TRUE, sep=";", na.strings="?")
Start <- strptime("01/02/2007", format='%d/%m/%Y')
End <- strptime("02/02/2007", format='%d/%m/%Y')
DataSort <- subset(Data, strptime(Data$Date, format='%d/%m/%Y')>=Start & strptime(Data$Date, format='%d/%m/%Y')<=End)
rm(Data)
DataSort$DateTime <- strptime(paste(DataSort$Date, DataSort$Time), format='%d/%m/%Y %H:%M:%S')
png(file="plot4.png",width=480,height=480)
par(mfrow=c(2,2))
with(DataSort, plot(DateTime, Global_active_power,type="l", ylab="Global Active Power (kilowatts)", xlab=""))
with(DataSort, plot(DateTime, Voltage ,type="l", ylab="Voltage", xlab="datetime"))
with(DataSort, plot(DateTime, Sub_metering_1,type="l", ylab="Energy sub metering", xlab=""))
with(DataSort, lines(DateTime, Sub_metering_2,type="l", col="red"))
with(DataSort, lines(DateTime, Sub_metering_3,type="l", col="blue"))
legend("topright", lty = 1, col = c("black", "blue", "red"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), bty = "n")
with(DataSort, plot(DateTime, Global_reactive_power,type="l", ylab="Global_Reactive_Power", xlab="datetime"))
dev.off()

