Data <- read.table(file="household_power_consumption.txt", header=TRUE, sep=";", na.strings="?")
Start <- strptime("01/02/2007", format='%d/%m/%Y')
End <- strptime("02/02/2007", format='%d/%m/%Y')
DataSort <- subset(Data, strptime(Data$Date, format='%d/%m/%Y')>=Start & strptime(Data$Date, format='%d/%m/%Y')<=End)
rm(Data)
DataSort$DateTime <- strptime(paste(DataSort$Date, DataSort$Time), format='%d/%m/%Y %H:%M:%S')
png(file="plot2.png",width=480,height=480)
with(DataSort, plot(DateTime, Global_active_power,type="l", ylab="Global Active Power (kilowatts)", xlab=""))
dev.off()
